/** This manifest is fingerprinted with each scan. Removing a rule cannot silently resolve its old finding. */
export const TS_RULES = [
  "TS_FLOATING_PROMISE", "TS_DETACHED_ASYNC", "TS_UNBOUNDED_FANOUT", "TS_TIMER_CLEANUP",
  "TS_LISTENER_CLEANUP", "TS_SUBSCRIPTION_CLEANUP", "TS_EMPTY_CATCH", "TS_ANY_BOUNDARY",
  "TS_TYPE_SUPPRESSION", "TS_DYNAMIC_CODE", "TS_ABORT_NOT_FORWARDED", "TS_SYNC_IO",
  "TS_UNVALIDATED_DESERIALIZATION", "TS_LAYER_VIOLATION", "TS_IMPORT_CYCLE", "TS_TEST_DISABLED",
  "TS_TEST_EXCLUSIVE", "TS_LARGE_FUNCTION", "TS_DUPLICATE_IMPLEMENTATION", "TS_NESTED_RETRY",
] as const;
export const CONFIG_RULES = [
  "CONFIG_TEST_SKIP", "CONFIG_FLOATING_DEPENDENCY", "CONFIG_FLOATING_IMAGE",
  "CONFIG_DESTRUCTIVE_MIGRATION", "CONFIG_UNBOUNDED_QUEUE", "CONFIG_PRIVATE_KEY",
] as const;
